
package ec.edu.espe.managamentsystem.view;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;

import ec.edu.espe.managmentsystem.model.User;
import ec.edu.espe.managmentsystem.util.MongoDBConnection;
import ec.edu.espe.managmentsystem.util.Validation;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.bson.Document;
/**
 *
 * @author Labs-DCCO
 */
public class FrmCreateUser extends javax.swing.JFrame {
MongoDBConnection db = new MongoDBConnection();
    /**
     * Creates new form FrmCreatUser
     */
    public FrmCreateUser() {
        initComponents();
        lblAlertID.setVisible(false);
        lblName.setVisible(false);
        lblemail.setVisible(false);
        lblpass.setVisible(false);
        lblphone.setVisible(false);
        lbluser.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCreatFullName = new javax.swing.JTextField();
        txtCreatePhoneNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCreateCedula = new javax.swing.JTextField();
        txtCreateEmail = new javax.swing.JTextField();
        cmbCharge = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCreateUsername = new javax.swing.JTextField();
        txtCreatPassword = new javax.swing.JTextField();
        lblAlertID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblphone = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        brnRegister = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jTextField2.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear Usuario");

        jLabel2.setText("Nombre completo:");

        jLabel3.setText("Cargo: ");

        jLabel5.setText("Teléfono celular: ");

        jLabel6.setText("Correo electrónico:");

        jLabel4.setText("Número de Cédula:");

        cmbCharge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Instructor" }));

        jLabel7.setText("Nombre de Usuario:");

        jLabel8.setText("Contraseña:");

        lblAlertID.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblAlertID.setText("*Campo Vacio por favor completar");

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblName.setText("*Campo Vacio por favor completar");

        lblphone.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblphone.setText("*Campo Vacio por favor completar");

        lbluser.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbluser.setText("*Campo Vacio por favor completar");

        lblemail.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblemail.setText("*Campo Vacio por favor completar");

        lblpass.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblpass.setText("*Campo Vacio por favor completar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCreatFullName)
                    .addComponent(txtCreatePhoneNumber)
                    .addComponent(txtCreateCedula)
                    .addComponent(txtCreateEmail)
                    .addComponent(txtCreateUsername)
                    .addComponent(cmbCharge, 0, 135, Short.MAX_VALUE)
                    .addComponent(txtCreatPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAlertID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblphone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbluser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCreateCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlertID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCreatFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCreatePhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblphone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCreateEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblemail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCreateUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbluser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCreatPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpass))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        brnRegister.setText("Registrar");
        brnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnRegisterActionPerformed(evt);
            }
        });

        btnBack.setText("Volver");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(brnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnRegisterActionPerformed
        Validation v = new Validation();
        String uri = "mongodb+srv://jmsanmartin:12345@managmentsystem.kklzuz1.mongodb.net/?retryWrites=true&w=majority";
        String db = "SchoolManagmentSystem";
        try(MongoClient mongoClient = MongoClients.create(uri)){
            MongoDatabase database = mongoClient.getDatabase(db);
            MongoCollection<Document> collection = database.getCollection("Users"); 
        User user;
        String id;
        String fullName;
        String cellphone;
        String email;
        String typeOfUser;
        String username;
        String password = null;
        String cadena;
        if(txtCreateCedula.getText().isEmpty()||txtCreatFullName.getText().isEmpty()
                ||txtCreatPassword.getText().isEmpty()||txtCreateEmail.getText().isEmpty()||
                txtCreateUsername.getText().isEmpty()||txtCreatePhoneNumber.getText().isEmpty()){
            lblAlertID.setVisible(true);
            lblName.setVisible(true);
            lblemail.setVisible(true);
            lblpass.setVisible(true);
            lblphone.setVisible(true);
            lbluser.setVisible(true);
                    
        }else{
            lblAlertID.setVisible(false);
            lblName.setVisible(false);
            lblemail.setVisible(false);
            lblpass.setVisible(false);
            lblphone.setVisible(false);
            lbluser.setVisible(false);
        }
        id = v.validateNumber(txtCreateCedula);
        fullName=v.validateName(txtCreatFullName);
        cellphone=v.validateNumber(txtCreatePhoneNumber);
        email=v.validateEmail(txtCreateEmail);
        typeOfUser=cmbCharge.getSelectedItem().toString();
        username=txtCreateUsername.getText();
        cadena = txtCreatPassword.getText();
        String cifrada = "";
        int desplazar = 2;

        for (int i = 0; i < cadena.length(); i++) {
        // Obtenemos el código ASCII de las letras de la cadena
        int codigoLetra = cadena.codePointAt(i);
        // Sumamos el desplazamiento al código y convertimos en char el resultado
        char letraDesplazada = (char)(codigoLetra + desplazar);
        // Concatenamos la letra obtenida a la cadena donde vamos cifrando
        cifrada = cifrada + letraDesplazada;
    }

    Document document = new Document("id", id)
            .append("fullName", fullName)
            .append("cellphone", cellphone)
            .append("email", email)
            .append("typeOfUser", typeOfUser)
            .append("username", username)
            .append("password", cifrada);


            collection.insertOne(document);
            System.out.println("Documento insertado correctamente en MongoDB");

        
        mongoClient.close();
    } catch (Exception e) {
        e.printStackTrace();
    }   
        JOptionPane.showMessageDialog(rootPane, "Saved");
        emptyField();
        
    }//GEN-LAST:event_brnRegisterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        FrmManagmentSystem frmManagmentSystem;
        frmManagmentSystem = new FrmManagmentSystem();
        frmManagmentSystem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    private void emptyField() {
        txtCreatFullName.setText(" ");
        txtCreatPassword.setText("");
        txtCreateCedula.setText("");
        txtCreateEmail.setText("");
        txtCreatePhoneNumber.setText("");
        txtCreateUsername.setText("");
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCreateUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnRegister;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbCharge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblAlertID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lbluser;
    private javax.swing.JTextField txtCreatFullName;
    private javax.swing.JTextField txtCreatPassword;
    private javax.swing.JTextField txtCreateCedula;
    private javax.swing.JTextField txtCreateEmail;
    private javax.swing.JTextField txtCreatePhoneNumber;
    private javax.swing.JTextField txtCreateUsername;
    // End of variables declaration//GEN-END:variables
}
