package ec.edu.espe.managamentsystem.view.holistic;

import ec.edu.espe.managamentsystem.controller.HolisticLegalGuardianController;
import ec.edu.espe.managamentsystem.controller.HolisticStudentController;
import ec.edu.espe.managamentsystem.controller.SearchController;
import ec.edu.espe.managmentsystem.util.Validation;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Oswaldo Tipan
 */
public class FrmDeleteStudentData extends javax.swing.JFrame {

    String name;
    FrmHolisticStudent frmHolisticStudentOrigin;

    public FrmHolisticStudent getFrmHolisticStudentOrigin() {
        return frmHolisticStudentOrigin;
    }

    public void setFrmHolisticStudentOrigin(FrmHolisticStudent frmHolisticStudentOrigin) {
        this.frmHolisticStudentOrigin = frmHolisticStudentOrigin;
    }

    /**
     * Creates new form FrmGetStudentData
     */
    public FrmDeleteStudentData() {
        initComponents();
        lblFound.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        lblFound = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nombre del estudiante:");

        txtStudentName.setForeground(new java.awt.Color(153, 153, 153));
        txtStudentName.setText("Ingrese el nombre del estudiante");
        txtStudentName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtStudentNameMouseClicked(evt);
            }
        });

        lblFound.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
        lblFound.setForeground(new java.awt.Color(255, 0, 0));
        lblFound.setText("*estudiante no encontrado");

        btnSearch.setBackground(new java.awt.Color(255, 102, 102));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 102, 102));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFound)
                            .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnSearch)
                        .addGap(32, 32, 32)
                        .addComponent(btnCancel)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFound)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnCancel))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        getData();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtStudentNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStudentNameMouseClicked
        txtStudentName.setText("");
        txtStudentName.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtStudentNameMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void getData() {
        Validation validation = new Validation();

        if (txtStudentName.getText().isEmpty()) {
            lblFound.setText("*Campo Obligatorio");
            lblFound.setVisible(true);
        } else {
            lblFound.setText("*estudiante no encontrado");
            lblFound.setVisible(false);

            name = validation.validateName(txtStudentName);

            HolisticStudentController holisticStudentController = new HolisticStudentController();
            boolean isFound = holisticStudentController.validateStudentData(name);

            SearchController searchController = new SearchController();
            searchController.fileWritter(name);

            if (isFound) {
                lblFound.setVisible(false);
                delete();
                this.setVisible(false);
                frmHolisticStudentOrigin.setVisible(false);

            } else {
                lblFound.setVisible(true);
            }
        }
    }

    public void delete() {

        HolisticStudentController holisticStudentController = new HolisticStudentController();
        HolisticLegalGuardianController holisticLegalGuardianController = new HolisticLegalGuardianController();

        int opc = JOptionPane.showConfirmDialog(rootPane, "Seguro que desea eliminar a " + name);

        if (opc == 0) {
            holisticStudentController.deleteHolisticStudent(holisticStudentController.getStudentId());
            holisticLegalGuardianController.deleteHolisticLegalGuardian(holisticStudentController.getStudentId() + 1);
            JOptionPane.showMessageDialog(rootPane, "Usuario " + name + " borrado con exito");

            FrmHolisticStudent frmHolisticStudent = new FrmHolisticStudent();

            frmHolisticStudent.setVisible(true);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDeleteStudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDeleteStudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDeleteStudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDeleteStudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDeleteStudentData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFound;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
